# Gitee Go CI/CD 流水线配置
# 文件位置: .gitee-ci.yml (仓库根目录)

version: '1.0'
name: CarbonOS Deploy Pipeline

# 触发条件
triggers:
  push:
    branches:
      - main
  manual: true

# 全局变量 (需要在 Gitee Go 后台设置对应的密钥变量)
variables:
  # 阿里云容器镜像服务
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  NAMESPACE: ${ALIYUN_NAMESPACE}
  IMAGE_PREFIX: carbonos

stages:
  - name: 构建镜像
    jobs:
      - name: Build and Push Images
        runs-on: docker
        steps:
          - name: 检出代码
            uses: checkout@v1

          - name: 登录阿里云镜像仓库
            run: |
              echo "${ALIYUN_REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u "${ALIYUN_REGISTRY_USERNAME}" --password-stdin

          - name: 构建并推送 Frontend
            run: |
              docker build -t ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-frontend:latest -f ./carbonos/Dockerfile ./carbonos
              docker push ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-frontend:latest

          - name: 构建并推送 Backend
            run: |
              docker build -t ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-backend:latest -f ./carbonos/backend/Dockerfile ./carbonos/backend
              docker push ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-backend:latest

  - name: 部署
    needs: 构建镜像
    jobs:
      - name: Deploy to Server
        runs-on: docker
        steps:
          - name: 检出代码
            uses: checkout@v1

          - name: 部署到服务器
            uses: ssh-deploy@v1
            with:
              host: ${SERVER_HOST}
              port: ${SERVER_PORT}
              username: ${SERVER_USER}
              privateKey: ${SSH_PRIVATE_KEY}
              script: |
                mkdir -p ~/apps/carbonos
                cd ~/apps/carbonos
                
                # 登录阿里云镜像仓库
                echo "${ALIYUN_REGISTRY_PASSWORD}" | docker login ${REGISTRY} -u "${ALIYUN_REGISTRY_USERNAME}" --password-stdin
                
                # 拉取最新镜像
                docker pull ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-frontend:latest
                docker pull ${REGISTRY}/${NAMESPACE}/${IMAGE_PREFIX}-backend:latest
                
                # 重启服务
                docker compose -f docker-compose.prod.yml up -d --remove-orphans
                
                # 数据库迁移
                sleep 10
                docker compose -f docker-compose.prod.yml exec -T backend alembic upgrade head
                
                # 清理
                docker image prune -f

          - name: 上传配置文件
            uses: scp@v1
            with:
              host: ${SERVER_HOST}
              port: ${SERVER_PORT}
              username: ${SERVER_USER}
              privateKey: ${SSH_PRIVATE_KEY}
              source: docker-compose.prod.yml,nginx/nginx.conf
              target: ~/apps/carbonos/
